itkdev_openid_connect:
    cache_options:
        cache_pool: 'cache.app' # Cache item pool for caching discovery document and CLI login tokens
    cli_login_options:
        cli_redirect: '%env(CLI_REDIRECT)%' # Redirect route for CLI login
    openid_providers:
        AzureAd:
            options:
                metadata_url: '%env(CONFIGURATION_URL)%' # url to OpenId Discovery document
                client_id: '%env(CLIENT_ID)%' # Client id assigned by authorizer
                client_secret: '%env(CLIENT_SECRET)%' # Client password assigned by authorizer
                redirect_uri: '%env(REDIRECT_URI)%' # Callback URI registered at identity provider
